set-option -g default-shell /opt/homebrew/bin/fish
set -g mouse on
set -s set-clipboard on
set -s escape-time 0

bind -n m-z split-window -v -l 15 -c "#{pane_current_path}"

set -g status-style bg=default,fg=default

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n -r M-b resize-pane -L 5
bind -n -r M-n resize-pane -D 5
bind -n -r M-m resize-pane -U 5
bind -n -r M-, resize-pane -R 5

bind -n M-v split-window -h -c "#{pane_current_path}"

bind -n m-c split-window -h -l 30% -c "#{pane_current_path}"

unbind -n C-Left
unbind -n M-Left
unbind -n M-Right
unbind -n M-Up
unbind -n M-Down

# Stop Option/Alt+Arrows from resizing panes (prefix table)
unbind -T prefix M-Left
unbind -T prefix M-Right
unbind -T prefix M-Up
unbind -T prefix M-Down

# (Optional) also ensure they are not bound in root
unbind -n M-Left
unbind -n M-Right
unbind -n M-Up
unbind -n M-Down

unbind -n M-b
unbind -n M-f  # only if you bound it elsewhere

# Also remove your repeatable resize binds
unbind -n M-b
unbind -n  M-n
unbind -n  M-m
unbind -n M-,

