set-option -g default-shell /opt/homebrew/bin/fish
set -g mouse on
set -s set-clipboard on

bind -n M-t split-window -v -l 15 -c "#{pane_current_path}"

set -g status-style bg=default,fg=default

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-v split-window -h -c "#{pane_current_path}"

bind -n m-c split-window -h -l 30% -c "#{pane_current_path}"
