theme = "carbonfox"
[editor]
clipboard-provider = "termcode"
default-yank-register = "+"

[keys.normal]
"A-s" = ":w"


[keys.select]
"A-x" = "normal_mode"
"esc" = "no_op"

[keys.insert]
"A-x" = "normal_mode"
"esc" = "no_op"

