theme = "carbonfox"
[editor]
clipboard-provider = "termcode"
default-yank-register = "+"
auto-completion = false

[keys.normal]
"A-s" = ":w"
"C-s" = [
  ":insert-output echo '### Productivity\n\n### Chores\n\n### Amazon\n'"
]

[keys.select]
"A-x" = "normal_mode"
"esc" = "no_op"

[keys.insert]
"A-x" = "normal_mode"
"esc" = "no_op"

